version: "3"
services:
  app:
    image: eserian/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    ports:
      - "8080:8080"
    volumes: 
      - "./app:/app"