name: ci
on: push

env:
  APP_IMAGE_NAME: akryvaruchka/hexlet-js-fastify-blog

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build App
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.production
        cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
        cache-to: type=inline
        push: true
        tags: ${{ env.APP_IMAGE_NAME }}:cached

    - name: Check
      run: make ci

    - name: Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.production
        cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
        push: true
        tags: ${{ env.APP_IMAGE_NAME }}:latest