name: ci
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build App
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.production
        cache-from: type=registry,ref=eserian/devops-for-programmers-project-lvl1:cached
        cache-to: type=inline
        push: true
        tags: eserian/devops-for-programmers-project-lvl1:cached

    - name: Check
      run: |
          make ci

    - name: Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.production
        cache-from: type=registry,ref=eserian/devops-for-programmers-project-lvl1:cached
        push: true
        tags: eserian/devops-for-programmers-project-lvl1:latest